# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'rmagick'

file = File.open("app/assets/documents/test.pdf")
pdf = Magick::ImageList.new("app/assets/documents/test.pdf")
thumb = pdf.scale(340, 440)
thumb.write "app/assets/documents/test.png"
User.create(email: "oscar@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
User.create(email: "oscar1@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy1@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian1@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
User.create(email: "oscar11@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy11@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian11@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
User.create(email: "oscar111@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy111@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian111@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
User.create(email: "oscar1111@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy1111@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian1111@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
User.create(email: "oscar11111@oscar.cl", name: "Oscar", last_name: "Estay", password: "password", password_confirmation: "password", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "germy11111@germy.cl", name: "German", last_name: "Contreras", password: "123456", password_confirmation: "123456", avatar: File.new("app/assets/images/bad_joke.png"), admin: true)
User.create(email: "bastian11111@bastian.cl", name: "Bastian", last_name: "Mavrakis", password: "lalala", password_confirmation: "lalala", avatar: File.new("app/assets/images/bad_joke.png"), admin: false)
@user1 = User.find(1)
@user2 = User.find(2)
@user3 = User.find(3)
@user4 = User.find(4)
@user5 = User.find(5)
@user6 = User.find(6)
@user7 = User.find(7)
@user8 = User.find(8)
@user9 = User.find(9)
@user10 = User.find(10)
@user11 = User.find(11)
@user12 = User.find(12)
@user13 = User.find(13)
@user14 = User.find(14)
@user15 = User.find(15)
@user16 = User.find(16)
@user17 = User.find(17)
@user18 = User.find(18)
Book.create(uploader_id: 1, name: "Test 0", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 1", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 2", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 3", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 4", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 5", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 6", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 7", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 8", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 9", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 10", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 11", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 12", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 13", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 14", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 15", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 16", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 17", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 0", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 1", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 2", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 3", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 4", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 5", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 6", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 7", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 8", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 9", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 10", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 11", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 12", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 13", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 14", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 15", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 16", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 17", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 0", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 1", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 2", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 3", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 4", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 5", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 6", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 7", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 8", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 9", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 10", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 11", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 12", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 13", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 14", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 15", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 16", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 17", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 0", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 1", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 2", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 3", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 4", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 1, name: "Test 5", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 6", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 7", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 8", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 9", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 10", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 2, name: "Test 11", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 12", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 13", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 14", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 15", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 16", private: true, document: file, thumbnail: File.new("app/assets/documents/test.png"))
Book.create(uploader_id: 3, name: "Test 17", private: false, document: file, thumbnail: File.new("app/assets/documents/test.png"))

Tag.create(name:"Science Fiction")
Tag.create(name:"Fantasy")
Tag.create(name:"Satire")
Tag.create(name:"Drama")
Tag.create(name:"Action & Adventure")
Tag.create(name:"Romance")
Tag.create(name:"Mystery")
Tag.create(name:"Horror")
Tag.create(name:"Self Help & Health")
Tag.create(name:"Guide & Travel")
Tag.create(name:"Children")
Tag.create(name:"Religion")
Tag.create(name:"Math & Science")
Tag.create(name:"History")
Tag.create(name:"Poetry & Art")
Tag.create(name:"Encyclopedias")
Tag.create(name:"Dictionaries")
Tag.create(name:"Comics")
Tag.create(name:"Cookbooks")
Tag.create(name:"Diaries & Journals")
Tag.create(name:"Biographies")

# Add three random tags per book
@books = Book.all
@tags = Tag.all

@books1 = @books.where('uploader_id = 1')
@books1.each do |book|
  @user1.books << book
end

@books2 = @books.where('uploader_id = 2')
@books2.each do |book|
  @user2.books << book
end

@books3 = @books.where('uploader_id = 3')
@books3.each do |book|
  @user3.books << book
end

@user1.books.each do |book|
  book.tags = @tags.sample(3)
end

@user2.books.each do |book|
  book.tags = @tags.sample(3)
end

@user3.books.each do |book|
  book.tags = @tags.sample(3)
end
Book.all.each do |libro|
	@user1.rate!(libro,Random.new.rand(1..4))
	@user2.rate!(libro,Random.new.rand(1..4))
	@user3.rate!(libro,Random.new.rand(1..4))
	@user4.rate!(libro,Random.new.rand(1..4))
	@user5.rate!(libro,Random.new.rand(1..4))
	@user6.rate!(libro,Random.new.rand(1..4))
	@user7.rate!(libro,Random.new.rand(1..4))
	@user8.rate!(libro,Random.new.rand(1..4))
	@user9.rate!(libro,Random.new.rand(1..4))
	@user10.rate!(libro,Random.new.rand(1..4))
	@user11.rate!(libro,Random.new.rand(1..4))
	@user12.rate!(libro,Random.new.rand(1..4))
	@user13.rate!(libro,Random.new.rand(1..4))
	@user14.rate!(libro,Random.new.rand(1..4))
	@user15.rate!(libro,Random.new.rand(1..4))
	@user16.rate!(libro,Random.new.rand(1..4))
	@user17.rate!(libro,Random.new.rand(1..4))
	@user18.rate!(libro,Random.new.rand(1..4))
end
file.close
